"""empty message

Revision ID: 7ec208412773
Revises: 12d9e644678c
Create Date: 2021-09-02 23:23:02.151950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec208412773'
down_revision = '12d9e644678c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servant', sa.Column('master_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servant', 'master', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servant', type_='foreignkey')
    op.drop_column('servant', 'master_id')
    # ### end Alembic commands ###
